// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string):Promise<void>;

export function CompleteTask(arg1:number):Promise<void>;

export function FeedPet():Promise<main.PetState>;

export function GetPetState():Promise<main.PetState>;

export function GetTasks():Promise<Array<string>>;

export function GiveTreat():Promise<main.PetState>;

export function Mood():Promise<string>;

export function PutPetToSleep():Promise<main.PetState>;
